services:
  db:
    image: postgres:14.19-alpine3.21
    container_name: vacation_db
    restart: always
    environment:
      POSTGRES_DB: vacationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: vacation_backend
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      - DB_NAME=vacationdb
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - PORT=4000
    volumes:
      - ./server:/app
    command: sh -c "npm run dev"

  frontend:
    build: ./client
    container_name: vacation_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000/api
    volumes:
      - ./client:/app

volumes:
  db_data: